routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::get('/reservation', 'AdminReservationController@index');
Route::get('/show/{id}', 'AdminReservationController@reservation_show');
Route::post('/reservation/{id}', 'AdminReservationController@status')->name('reservation.status');
Route::delete('/reservation/{id}', 'AdminReservationController@destroy')->name('reservation.destroy');
Route::post('/contact', 'ContactController@sendMessage')->name('contact.send');
Route::get('/dashboard/category', 'DashboardController@category');
Route::get('/view-details/{id}', 'ViewDetailsController@view_details');



Route::resource('/slider', 'SliderController');
Route::resource('/category', 'CategoryController');
Route::resource('/item', 'ItemController');
Route::resource('/admin/contact', 'AdminContactController');
Route::resource('/new', 'NewController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public function category()
    {
    	return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use App\Category;
use Carbon\Carbon;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::all();
        return view('item.item_index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
       return view('item.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $this->validate($request, [
            'category_id'=>'required',
            'name'=>'required',
            'description'=>'required',
            'price'=>'required',
            'image'=>'required|mimes:png,jpeg,jpg',
        ]);
        $image= $request->file('image');
        $slug= str_slug($request->name);
        if (isset($image))
        {
            $currentDate= Carbon::now()->toDateString();
            $imagename= $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!file_exists('uploads/image')) 
            {
                mkdir('uploads/image', 0777, true);
            }
                $image->move('uploads/image', $imagename);
        }else{
            $imagename='default.png';
        }

        $item = new Item();
        $item->category_id = $request->category_id;
        $item->name = $request->name;
        $item->description = $request->description;
        $item->price = $request->price;
        $item->image= $imagename;
        $item->save();

        return redirect()->route('item.index')->with('messageMsg','Saved successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Item::find($id);
        return view('partial.view_detail', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items=Item::find($id);
        $categories=Category::find($id);
        return view('item.edit', compact('items', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'=>'required',
            'description'=>'required',
            'price'=>'required',
            'image'=>'mimes:png,jpeg,jpg',
        ]);
        $item = Item::find($id);
        $image= $request->file('image');
        $slug= str_slug($request->name);
        if (isset($image))
        {
            $currentDate= Carbon::now()->toDateString();
            $imagename= $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!file_exists('uploads/image')) 
            {
                mkdir('uploads/image', 0777, true);
            }
                unlink('uploads/image/'.$item->image);
                $image->move('uploads/image', $imagename);
        }else{
            $imagename=$item->image;
        }

        
        $item->name = $request->name;
        $item->description = $request->description;
        $item->price = $request->price;
        $item->image= $imagename;
        $item->save();

        return redirect()->route('item.index')->with('messageMsg','Saved successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $item=Item::find($id);
        if (file_exists('uploads/image/'.$item->image)) {
            
            unlink('uploads/image/'.$item->image);
        }
        $item->delete();

        return redirect()->back()->with('messageMsg','Deleted successfully');
    }
}

resources/views/item/create.blade.php
@extends('admin.dashboard')

@push('css')


@endpush

@section('content')

    <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                           @include('partial.message')
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Add Item</h4>
                                    <p class="category">Here is a subtitle for this table</p>
                                </div>
                                <div class="card-content table-responsive">
                                    <form method="post" action="{{ route('item.store') }}" enctype="multipart/form-data"> 
                                        @csrf
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Category</label>
                                                    <select class="form-control" name="category_id">
                                                               <option>select Category</option>
                                                        @foreach($categories as $category)
                                                            <option value="{{$category->id}}">{{ $category->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Name</label>
                                                    <input type="text" name="name" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Description</label>
                                                    <textarea type="text" name="description" class="form-control"></textarea>
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">price</label>
                                                    <input type="number" name="price" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                    <label class="control-label">Image</label>
                                                    <input type="file" name="image">
                                                </div>
                                            </div>
                                            <a href="{{ route('item.index') }}" class="btn btn-info">Back</a>
                                            <button type="submit" class="btn btn-primary">Save</button>        
                                        </div> 
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>

@endsection


resources/views/item/edit.blade.php
@extends('admin.dashboard')

@push('css')


@endpush

@section('content')

    <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                           @include('partial.message')
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Add Item</h4>
                                    <p class="category">Here is a subtitle for this table</p>
                                </div>
                                <div class="card-content table-responsive">
                                    <form method="post" action="{{ route('item.update', $items->id) }}" enctype="multipart/form-data"> 
                                        @csrf
                                        @method('PUT')
                                        
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Name</label>
                                                    <input type="text" name="name" class="form-control" value="{{$items->name}}">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Description</label>
                                                    <input type="text" name="description" class="form-control" value="{{$items->description}}"></input>
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">price</label>
                                                    <input type="number" name="price" class="form-control" value="{{$items->price}}">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                    <label class="control-label">Image</label>
                                                    <input type="file" name="image">
                                                </div>
                                            </div>
                                            <a href="{{ route('item.index') }}" class="btn btn-info">Back</a>
                                            <button type="submit" class="btn btn-primary">Save</button>        
                                        </div> 
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>

@endsection


resources/views/item/item_index.blade.php
@extends('admin.dashboard')

@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">

@endpush

@section('content')

    <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                        	<a href="{{ route('item.create') }}" class="btn btn-primary">Create New Item</a>
                        	@include('partial.message')
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">All Items</h4>
                                    <p class="itemegory">Here is a subtitle for this table</p>
                                </div>
                                <div class="card-content table-responsive">
                                    <table id="table" class="table table-striped" style="width:100%">
                                        <thead class="text-primary">
		                                    <th>SL No</th>
		                                    <th>Category</th>
		                                    <th>Item Name</th>
		                                    <th>Image</th>
		                                    <th>Description</th>
		                                    <th>Price</th>
		                                    <th>Action</th>
                                        </thead>
                                        <tbody>
                                            @foreach($items as $key=>$item)
		                                    <tr>
		                                       <td>{{ $key +1 }}</td>
		                                       <td>{{ $item->category->name }}</td>
		                                       <td>{{ $item->name }}</td>
		                                       <td><img class="img-responsive img-thumbnail" src="{{ asset('uploads/image/'. $item->image)  }}" style="height: 100px; width: 100px;">
		                                       </td>
		                                       <td>{{ $item->description }}</td>
		                                       <td>{{ $item->price }}</td>
		                                       <td>
		                                       	<a href="{{ route('item.edit', $item->id ) }}" class="btn btn-success btn-sm"><i class="material-icons">edit</i></a>

		                                       	<form action="{{ route('item.destroy', $item->id) }}" style="display: none;" id="delete-form-{{ $item->id }}" method="POST">
		                                       		@csrf
		                                       		@method('DELETE')
		                                       		
		                                       	</form>
		                                 
			                                       <button class="btn btn-danger btn-sm" type="button" onclick="if (confirm('Are you sure want to delete this?')) {
			                                       		event.preventDefault();
			                                       		document.getElementById('delete-form-{{ $item->id }}').submit();

			                                       } else {
			                                       	event.preventDefault();
			                                       }" ><i class="material-icons">delete</i>
			                                       	
			                                       </button>
		                                       </td>
		                                    </tr>
		                                    @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>

@endsection

@push('scripts')
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
<script>
	$(document).ready(function() {
    $('#table').DataTable();
} );
</script>

@endpush

resources/views/item/new.blade.php
@extends('admin.dashboard')

@push('css')


@endpush

@section('content')

    <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                           @include('partial.message')
                            <div class="card">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Add Item</h4>
                                    <p class="category">Here is a subtitle for this table</p>
                                </div>
                                <div class="card-content table-responsive">
                                    <form method="post" action="{{ route('new.store') }}" enctype="multipart/form-data"> 
                                        @csrf
                                        
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Name</label>
                                                    <input type="text" name="name" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">Description</label>
                                                    <textarea type="text" name="description" class="form-control"></textarea>
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">price</label>
                                                    <input type="number" name="price" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">address</label>
                                                    <input type="text" name="address" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group label-floating">
                                                    <label class="control-label">phone</label>
                                                    <input type="number" name="phone" class="form-control">
                                                </div>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            
                                            <a href="{{ route('new.index') }}" class="btn btn-info">Back</a>
                                            <button type="submit" class="btn btn-primary">Save</button>        
                                        </div> 
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>

@endsection