routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/reservation', 'ReservationController@reserve')->name('reservation.reserve');
Route::get('/reservation', 'AdminReservationController@index');
Route::get('/show/{id}', 'AdminReservationController@reservation_show');
Route::post('/reservation/{id}', 'AdminReservationController@status')->name('reservation.status');
Route::delete('/reservation/{id}', 'AdminReservationController@destroy')->name('reservation.destroy');
Route::post('/contact', 'ContactController@sendMessage')->name('contact.send');
Route::get('/dashboard/category', 'DashboardController@category');
Route::get('/view-details/{id}', 'ViewDetailsController@view_details');



Route::resource('/slider', 'SliderController');
Route::resource('/category', 'CategoryController');
Route::resource('/item', 'ItemController');
Route::resource('/admin/contact', 'AdminContactController');
Route::resource('/new', 'NewController');

resources/views/partial/content.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="orange">
                    <i class="material-icons">content_copy</i>
                </div>
                <?php 
                    $category=DB::table('categories')
                    ->get()
                  
                 ?>
                <div class="card-content">
                    <p class="category">Total Category</p>
                    
                    <h3 class="title">{{$category->count()}}
                        <small>GB</small>
                    </h3>
                   
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons text-danger">warning</i>
                        <a href="#pablo">Get More Space...</a>
                    </div>
                </div>
            </div>
        </div>
         <?php 
                    $reserve=DB::table('reservations')
                    ->where('status', false)
                    ->get();
                  
                 ?>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="green">
                    <i class="material-icons">store</i>
                </div>
                <div class="card-content">
                    <p class="category">Reservation Pending</p>
                    <h3 class="title">{{ $reserve->count() }}</h3>
                    
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">date_range</i> Last 24 Hours
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header" data-background-color="red">
                    <i class="material-icons">info_outline</i>
                </div>
                <div class="card-content">
                    <p class="category">Fixed Issues</p>
                    <h3 class="title">75</h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">local_offer</i> Tracked from Github
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-6 col-md-12">
        
        </div>    
    </div>
</div>

resources/views/partial/footer.blade.php
 <footer class="footer">
                    <div class="container-fluid">
                        <nav class="pull-left">
                            <ul>
                                <li>
                                    <a href="#">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Company
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Portfolio
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Blog
                                    </a>
                                </li>
                            </ul>
                        </nav>
                        <p class="copyright pull-right">
                            &copy;
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </div>
                </footer>

resources/views/partial/message.blade.php
 @if ($errors->any())
        <ul>
            @foreach ($errors->all() as $error)
             
        <div class="alert alert-danger">
            <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none';">×</button>
            <span>
                <b> Danger - </b> {{ $error }}</span>
        </div>
            @endforeach
        </ul>
@endif

@if(session('messageMsg'))
    <div class="alert alert-success">
        <button type="button" aria-hidden="true" class="close" onclick="this.parentElement.style.display='none';">×</button>
        <span>
            <b> OK - </b> {{ session('messageMsg') }}</span>
    </div>
@endif

resources/views/partial/sidebar.blade.php
<div class="sidebar" data-color="purple" data-image="{{asset('backend/img/sidebar-1.jpg')}}">
                <div class="logo">
                    <a href="#" class="simple-text">
                        <strong> BURGER HOUSE</strong>
                    </a>
                </div>
                <div class="sidebar-wrapper">
                    <ul class="nav">
                        <li class="{{ Request::is('home*') ? 'active': '' }}">
                            <a href="{{ route('home') }}">
                                <i class="material-icons">dashboard</i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li class="{{ Request::is('slider*') ? 'active': '' }}">
                            <a href="{{ route('slider.index') }}">
                                <i class="material-icons">slideshow</i>
                                <p>All sliders</p>
                            </a>
                        </li>
                        <li class="{{ Request::is('category*') ? 'active': '' }}">
                            <a href="{{route('category.index')}}">
                                <i class="material-icons">view_list</i>
                                <p>All Categories</p>
                            </a>
                        </li>
                        <li class="{{ Request::is('item*') ? 'active': '' }}">
                            <a href="{{route('item.index')}}">
                                <i class="material-icons">view_list</i>
                                <p>All Items</p>
                            </a>
                        </li>
                        <li class="{{ Request::is('reservation*') ? 'active': '' }}">
                            <a href="{{URL::to('/reservation')}}">
                                <i class="material-icons">work</i>
                                <p>Reservation</p>
                            </a>
                        </li>
                        <li class="{{ Request::is('admin/contact*') ? 'active': '' }}">
                            <a href="{{URL::to('/admin/contact')}}">
                                <i class="material-icons">message</i>
                                <p>Contact Message</p>
                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>

resources/views/partial/topbar.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><marquee>  Welcome To<strong> BURGER HOUSE</strong></marquee></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                 <li class="dropdown">
                    <a  data-toggle="dropdown" href="#">
                        <i class="material-icons">web</i>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Facebook Page</a>
                            <div class="divider"></div>
                            <a href="#">Website</a>
                           
                        </li>
                    </ul>
                </li>  
                <li class="dropdown">
                    <a  data-toggle="dropdown" href="#">
                        <i class="material-icons">settings</i>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Company Profile</a>
                            <div class="divider"></div>
                            <a href="#">Status</a>                           
                        </li>
                    </ul>
                </li>  
                 
                <?php 
                    $contact=DB::table('contacts')->get();
                 ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">notifications</i>
                        <span class="notification">{{ $contact->count() }}</span>
                        <p class="hidden-lg hidden-md">Notifications</p>
                    </a>
                    <ul class="dropdown-menu">
                        @foreach($contact as $con)
                        <li>
                            <a href="{{ route('contact.show', $con->id) }}">{{ $con->name }}</a>
                        </li>
                        @endforeach
                        
                    </ul>
                </li>                             
                <li class="dropdown">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="material-icons">supervisor_account  </i> {{ Auth::user()->name }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Profile</a>
                            <div class="divider"></div>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                Logout
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>  
            </ul>
        </div>
    </div>
</nav>

resources/views/partial/view_detail.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="shortcut icon" href="{{asset('frontend/images/star.png')}}" type="favicon/ico" />  -->

        <title>Reservation</title>

        <link rel="stylesheet" href="{{asset('frontend/css/bootstrap.min.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/font-awesome.min.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/owl.carousel.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/owl.theme.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/animate.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/flexslider.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/pricing.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/main.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/bootstrap-datetimepicker.min.css')}}">
        <link rel="stylesheet" href="{{asset('frontend/css/toastr.min.css')}}">
    

        
        <script src="{{asset('frontend/js/jquery-1.11.2.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('frontend/js/jquery.flexslider.min.js')}}"></script>
     

    </head>
    <body data-spy="scroll" data-target="#template-navbar">

<section id="pricing" class="pricing">
            <div id="w">
                <div class="pricing-filter">
                    <div class="pricing-filter-wrapper">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    <div class="section-header">
                                        <h2 class="pricing-title">Have A Look To Dishe</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
               
                    </div>
                </div>      
            </div> 
        </section>
         <section id="have-a-look" class="have-a-look hidden-xs">
            <img class="img-responsive section-icon hidden-sm hidden-xs" src="">
            <div class="wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="menu-gallery" style="width: 50%; float:left;">
                            <div class="flexslider-container">
                                <div class="flexslider">
                                    <img src="{{asset('uploads/image/'.$item->image)}}" class="img-responsive" alt="Food" style="height: 685px; width: 743px; margin-top: 5px;">
                                </div>
                            </div>
                        </div>
                       <div class="col-xs-12 col-sm-6 dis-table-cell">
                            <div class="section-content">
                                <h1><b>Menu Details</b> </h1>
                                <h3 class="section-content-para">
                                   <b> Menu Name :</b> {{ $item->name  }}
                                </h3>
                                <h4 class="section-content-para">
                                    <b> Details :</b> {{ $item->description  }}.jkjkjlksaklkdjfkdjfkd djfdjf df fjdhfjd fjdf uhfds yue yui uiyuifsyidf uisfdsuiy fu oi oauidyf uiaoiuyduiyfuiaoiu uiui  iuy a uiuifiuayofuidy fuiaiudfyiuadfuiaiudsfuiyiuasdyfdayfu auifyuid yfuiuidyfuiyauidyfuiaduifyadufuiaydfuiyadf udyf  uidyfuid fuidyf iuy fuiaf 
                                </h4>
                                <br><br><br>
                                <a href="{{ URL::to('/') }}" class="btn btn-success btn-sm">Back to Main Page</a>
                            </div>

                        </div>
                        <footer>
                             <div class="container">
                                <div class="row">
                                    <div class="col-md-6 col-md-offset-3">
                                        <div class="copyright text-center">
                                            <p>
                                                &copy; Copyright, 2015 <a href="#">Your Website Link.</a> Theme by <a href="http://themewagon.com/"  target="_blank">ThemeWagon</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </footer>
                    </div> <!-- /.row -->
                </div> <!-- /.container-fluid -->
            </div> <!-- /.wrapper -->
        </section>
    
        <script src="{{asset('frontend/js/bootstrap.min.js')}}"></script>
        <script src="{{asset('frontend/js/owl.carousel.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('frontend/js/jquery.mixitup.min.js')}}" ></script>
        <script src="{{asset('frontend/js/wow.min.js')}}"></script>
        <script src="{{asset('frontend/js/jquery.validate.js')}}"></script>
        <script type="text/javascript" src="{{asset('frontend/js/jquery.hoverdir.js')}}"></script>
        <script type="text/javascript" src="{{asset('frontend/js/jQuery.scrollSpeed.js')}}"></script>
        <script src="{{asset('frontend/js/script.js')}}"></script>
        <script src="{{asset('frontend/js/bootstrap-datetimepicker.min.js')}}"></script>
        <script src="{{asset('frontend/js/toastr.min.js')}}"></script>       

    </body>
</html>